server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  application:
    name: api-gateway

services:
  directory:
    url: http://localhost:8081
  processing-core:
    url: http://localhost:8082

---
spring:
  config:
    activate:
      on-profile: docker

services:
  directory:
    url: http://directory:8081
  processing-core:
    url: http://processing-core:8082
